services:
  postgres-request:
    image: postgres:16
    container_name: postgres-request
    environment:
      POSTGRES_DB: image-request
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_request_data:/var/lib/postgresql/data

  postgres-validate:
    image: postgres:16
    container_name: postgres-validate
    environment:
      POSTGRES_DB: image-validate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_validate_data:/var/lib/postgresql/data

  postgres-generate:
    image: postgres:16
    container_name: postgres-generate
    environment:
      POSTGRES_DB: image-generate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_generate_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  image-request:
    container_name: image-request
    build: ./image-request
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres-request
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: jdbc:postgresql://postgres-request:5432/image-request

  image-validate:
    container_name: image-validate
    build: ./image-validate
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres-validate
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: jdbc:postgresql://postgres-validate:5432/image-validate
      JWT_SECRET: S3cre7key
      REDIS_HOST: redis

  image-generate:
    container_name: image-generate
    build: ./image-generate
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres-generate
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: jdbc:postgresql://postgres-generate:5432/image-generate

volumes:
  postgres_request_data:
  postgres_validate_data:
  postgres_generate_data:
  redis_data:
  redisinsight_data: