spring:
  application:
    name: image-validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/image-validate}
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

api:
  security:
    token:
      secret: ${JWT_SECRET:S3cre7key}

server:
  port: '8081'
