spring:
  application:
    name: request

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/image-request}
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

server:
  port: '8080'